### ISSUE TITLE
iDynTree installation via colcon?

### ISSUE THREAD

**Issue by traversaro** [nicholaspalomo/panda_ros2_gazebo#1]
Hi @nicholaspalomo, I found out this project via https://github.com/robotology/idyntree/issues/878, it seems quite nice!

I have just a small curiosity regarding the README: given that you are already installing some other dependencies from source via colcon, there is any reason why you build iDynTree from source in a separate step?

**Comment by nicholaspalomo** [comment]
Thanks for the comment, @traversaro. Hm... I guess I didn't have a particular reason other than that I guess I figured at the time that since it wasn't strictly a ROS package maybe it would be better to leave it out of the colcon workspace. But now that I reconsider it, it does make more sense to have it built with the other packages.

To be honest, I'm a little new to writing the `setup.py` (I'm used to ROS1 and using CMakeLists), so sorry if this is a basic question - if I put iDynTree in my colcon `src` directory, when I run the build command, will it automatically pass the `IDYNTREE_USES_IPOPT` option to the module?
